/// City option used by the project/address city picker.
///
/// [state] mirrors the web app's city→state mapping so picking a city can
/// auto-fill its state, matching `mob-web`'s `handleCityChange` behavior.
class CityOption {
  const CityOption(this.label, this.state) : value = label;

  final String label;
  final String value;
  final String state;
}

/// Ported from mob-web's `cityOptions` (src/shared/Constants.js).
const List<CityOption> kIndianCityOptions = [
  CityOption('Delhi', 'Delhi'),
  CityOption('Mumbai', 'Maharashtra'),
  CityOption('Kolkata', 'West Bengal'),
  CityOption('Bengaluru', 'Karnataka'),
  CityOption('Chennai', 'Tamil Nadu'),
  CityOption('Hyderabad', 'Telangana'),
  CityOption('Pune', 'Maharashtra'),
  CityOption('Ahmedabad', 'Gujarat'),
  CityOption('Surat', 'Gujarat'),
  CityOption('Lucknow', 'Uttar Pradesh'),
  CityOption('Jaipur', 'Rajasthan'),
  CityOption('Kanpur', 'Uttar Pradesh'),
  CityOption('Mirzapur', 'Uttar Pradesh'),
  CityOption('Nagpur', 'Maharashtra'),
  CityOption('Ghaziabad', 'Uttar Pradesh'),
  CityOption('Supaul', 'Bihar'),
  CityOption('Vadodara', 'Gujarat'),
  CityOption('Rajkot', 'Gujarat'),
  CityOption('Visakhapatnam', 'Andhra Pradesh'),
  CityOption('Indore', 'Madhya Pradesh'),
  CityOption('Thane', 'Maharashtra'),
  CityOption('Bhopal', 'Madhya Pradesh'),
  CityOption('Pimpri-Chinchwad', 'Maharashtra'),
  CityOption('Patna', 'Bihar'),
  CityOption('Bilaspur', 'Chhattisgarh'),
  CityOption('Ludhiana', 'Punjab'),
  CityOption('Agra', 'Uttar Pradesh'),
  CityOption('Madurai', 'Tamil Nadu'),
  CityOption('Jamshedpur', 'Jharkhand'),
  CityOption('Prayagraj', 'Uttar Pradesh'),
  CityOption('Nashik', 'Maharashtra'),
  CityOption('Faridabad', 'Haryana'),
  CityOption('Meerut', 'Uttar Pradesh'),
  CityOption('Jabalpur', 'Madhya Pradesh'),
  CityOption('Kalyan', 'Maharashtra'),
  CityOption('Vasai-Virar', 'Maharashtra'),
  CityOption('Najafgarh', 'Delhi'),
  CityOption('Varanasi', 'Uttar Pradesh'),
  CityOption('Srinagar', 'Jammu and Kashmir'),
  CityOption('Aurangabad', 'Maharashtra'),
  CityOption('Dhanbad', 'Jharkhand'),
  CityOption('Amritsar', 'Punjab'),
  CityOption('Aligarh', 'Uttar Pradesh'),
  CityOption('Guwahati', 'Assam'),
  CityOption('Howrah', 'West Bengal'),
  CityOption('Ranchi', 'Jharkhand'),
  CityOption('Gwalior', 'Madhya Pradesh'),
  CityOption('Chandigarh', 'Chandigarh'),
  CityOption('Haldwani', 'Uttarakhand'),
  CityOption('Vijayawada', 'Andhra Pradesh'),
  CityOption('Jodhpur', 'Rajasthan'),
  CityOption('Raipur', 'Chhattisgarh'),
  CityOption('Kota', 'Rajasthan'),
  CityOption('Bhayandar', 'Maharashtra'),
  CityOption('Loni', 'Uttar Pradesh'),
  CityOption('Ambattur', 'Tamil Nadu'),
  CityOption('Salt Lake City', 'West Bengal'),
  CityOption('Bhatpara', 'West Bengal'),
  CityOption('Kukatpalli', 'Telangana'),
  CityOption('Dasarhalli', 'Karnataka'),
  CityOption('Muzaffarpur', 'Bihar'),
  CityOption('Oulgaret', 'Puducherry'),
  CityOption('New Delhi', 'Delhi'),
  CityOption('Tiruvottiyur', 'Tamil Nadu'),
  CityOption('Puducherry', 'Puducherry'),
  CityOption('Byatarayanpur', 'Karnataka'),
  CityOption('Pallavaram', 'Tamil Nadu'),
  CityOption('Secunderabad', 'Telangana'),
  CityOption('Shimla', 'Himachal Pradesh'),
  CityOption('Puri', 'Odisha'),
  CityOption('Murtazabad', 'Karnataka'),
  CityOption('Shrirampur', 'West Bengal'),
  CityOption('Chandannagar', 'West Bengal'),
  CityOption('Sultampur Mazra', 'Uttar Pradesh'),
  CityOption('Krishnanagar', 'West Bengal'),
  CityOption('Barakpur', 'West Bengal'),
  CityOption('Bhalaswa Jahangirpur', 'Delhi'),
  CityOption('Nangloi Jat', 'Delhi'),
  CityOption('Balasore', 'Odisha'),
  CityOption('Dalupura', 'Delhi'),
  CityOption('Yelahanka', 'Karnataka'),
  CityOption('Titagarh', 'West Bengal'),
  CityOption('Dam Dam', 'West Bengal'),
  CityOption('Bansbaria', 'West Bengal'),
  CityOption('Madhavaram', 'Tamil Nadu'),
  CityOption('Abbigeri', 'Karnataka'),
  CityOption('Baj Baj', 'West Bengal'),
  CityOption('Garhi', 'Delhi'),
  CityOption('Mirpeta', 'Telangana'),
  CityOption('Nerkunram', 'Tamil Nadu'),
  CityOption('Kendrapara', 'Odisha'),
  CityOption('Sijua', 'Odisha'),
  CityOption('Manali', 'Himachal Pradesh'),
  CityOption('Kankuria', 'West Bengal'),
  CityOption('Chakapara', 'West Bengal'),
  CityOption('Pappakurichchi', 'Tamil Nadu'),
  CityOption('Herohalli', 'Karnataka'),
  CityOption('Madipakkam', 'Tamil Nadu'),
  CityOption('Sabalpur', 'West Bengal'),
  CityOption('Bauria', 'West Bengal'),
  CityOption('Salua', 'West Bengal'),
  CityOption('Chik Bnavar', 'Karnataka'),
  CityOption('Jalhalli', 'Karnataka'),
  CityOption('Chinnasekkadu', 'Tamil Nadu'),
  CityOption('Jethuli', 'Bihar'),
  CityOption('Nagtala', 'West Bengal'),
  CityOption('Pakri', 'Bihar'),
  CityOption('Hunasamaranhalli', 'Karnataka'),
  CityOption('Hesarghatta', 'Karnataka'),
  CityOption('Bommayapalaiyam', 'Tamil Nadu'),
  CityOption('Gundur', 'Karnataka'),
  CityOption('Punadih', 'Bihar'),
  CityOption('Hariladih', 'Bihar'),
  CityOption('Alawalpur', 'Uttar Pradesh'),
  CityOption('Madnaikanhalli', 'Karnataka'),
  CityOption('Bagalur', 'Karnataka'),
  CityOption('Kadiganahalli', 'Karnataka'),
  CityOption('Khanpur Zabti', 'Uttar Pradesh'),
  CityOption('Mahuli', 'Madhya Pradesh'),
  CityOption('Zeyadah Kot', 'Uttar Pradesh'),
  CityOption('Arshakunti', 'Karnataka'),
  CityOption('Mirchi', 'Karnataka'),
  CityOption('Sonudih', 'Bihar'),
  CityOption('Bayandhalli', 'Karnataka'),
  CityOption('Sondekoppa', 'Karnataka'),
  CityOption('Babura', 'Karnataka'),
  CityOption('Madavar', 'Karnataka'),
  CityOption('Kadabgeri', 'Karnataka'),
  CityOption('Nanmangalam', 'Tamil Nadu'),
  CityOption('Taliganja', 'Karnataka'),
  CityOption('Tarchha', 'Karnataka'),
  CityOption('Belgharia', 'West Bengal'),
  CityOption('Kammanhalli', 'Karnataka'),
  CityOption('Ambapuram', 'Andhra Pradesh'),
  CityOption('Sonnappanhalli', 'Karnataka'),
  CityOption('Kedihati', 'Karnataka'),
  CityOption('Doddajivanahalli', 'Karnataka'),
  CityOption('Simli Murarpur', 'West Bengal'),
  CityOption('Sonawan', 'Uttar Pradesh'),
  CityOption('Devanandapur', 'Karnataka'),
  CityOption('Tribeni', 'West Bengal'),
  CityOption('Huttanhalli', 'Karnataka'),
  CityOption('Nathupur', 'Haryana'),
  CityOption('Bali', 'Odisha'),
  CityOption('Vajarhalli', 'Karnataka'),
  CityOption('Alija Kotla', 'Karnataka'),
  CityOption('Saino', 'Karnataka'),
  CityOption('Shekhpura', 'Bihar'),
  CityOption('Cachoha', 'Uttar Pradesh'),
  CityOption('Andheri', 'Maharashtra'),
  CityOption('Narayanpur Kola', 'Karnataka'),
  CityOption('Gyan Chak', 'Bihar'),
  CityOption('Kasgatpur', 'Karnataka'),
  CityOption('Kitanelli', 'Karnataka'),
  CityOption('Harchandi', 'Karnataka'),
  CityOption('Santoshpur', 'West Bengal'),
  CityOption('Bendravadi', 'Karnataka'),
  CityOption('Kodagihalli', 'Karnataka'),
  CityOption('Harna Buzurg', 'Uttar Pradesh'),
  CityOption('Mailanhalli', 'Karnataka'),
  CityOption('Sultampur', 'Uttar Pradesh'),
  CityOption('Adakimaranhalli', 'Karnataka'),
  CityOption('Delhi NCR', 'Delhi'),
];

/// Ported from mob-web's `stateOptions` (src/shared/Constants.js),
/// de-duplicated ("Andhra Pradesh" appears twice in the source).
const List<String> kIndianStateOptions = [
  'Jammu and Kashmir',
  'Himachal Pradesh',
  'Punjab',
  'Chandigarh',
  'Uttarakhand',
  'Haryana',
  'Delhi',
  'Rajasthan',
  'Uttar Pradesh',
  'Bihar',
  'Sikkim',
  'Arunachal Pradesh',
  'Nagaland',
  'Manipur',
  'Mizoram',
  'Tripura',
  'Meghalaya',
  'Assam',
  'West Bengal',
  'Jharkhand',
  'Odisha',
  'Chhattisgarh',
  'Madhya Pradesh',
  'Gujarat',
  'Daman and Diu',
  'Dadra and Nagar Haveli',
  'Maharashtra',
  'Andhra Pradesh',
  'Karnataka',
  'Goa',
  'Lakshadweep',
  'Kerala',
  'Tamil Nadu',
  'Puducherry',
  'Andaman and Nicobar',
  'Telangana',
  'Ladakh',
];
